---
name: build-release
env:
  JAVA_VERSION: 17
  RUBY_VERSION: 3.2.1
  FLUTTER_VERSION: 3.7.6
on:
  push:
    branches:
      - main
jobs:
  check-tagged:
    name: checks tagged
    runs-on: macos-12
    environment: prod
    outputs:
      tagged: ${{ steps.gettag.outputs.tagged }}
      version: ${{ steps.gettag.outputs.version }}
    steps:
      - uses: actions/checkout@v2
      - name: get tag
        id: gettag
        shell: bash
        run: |
          echo "version=$(cat pubspec.yaml | grep version: | sed 's#version: ##' | tr -d '\n')" >> "$GITHUB_OUTPUT"
          git show-ref --tags --verify --quiet -- "refs/tags/v$(cat pubspec.yaml | grep version: | sed 's#version: ##' | tr -d '\n')" && echo 'tagged=0' >> "$GITHUB_OUTPUT" || echo 'tagged=1' >> "$GITHUB_OUTPUT"

  check-screenshots-and-icons:
    name: checks screenshots and icons
    runs-on: macos-12
    environment: prod
    needs: check-tagged
    outputs:
      screenshots-count: ${{ steps.screenshots.outputs.count }}
    steps:
      - uses: actions/checkout@v2
      - name: download android screenshots
        uses: dawidd6/action-download-artifact@v2
        id: check-exists
        with:
          workflow: build-release.yml
          github_token: ${{ secrets.GITHUB_TOKEN }}
          event: push
          branch: main
          name: android-screenshots-${{ needs.check-tagged.outputs.version }}
          path: android/fastlane/metadata/android/en-US/images/phoneScreenshots/
          search_artifacts: true
          if_no_artifact_found: ignore
      - name: get screenshots count
        id: screenshots
        shell: bash
        run: |
          echo "count=${{ steps.check-exists.outputs.found_artifact }}"
          echo "count=${{ steps.check-exists.outputs.found_artifact }}" >> "$GITHUB_OUTPUT"

  generate-screenshots-and-icons:
    name: generate screenshots
    runs-on: macos-12
    environment: prod
    needs:
      - check-tagged
      - check-screenshots-and-icons
    if: ${{ needs.check-tagged.outputs.tagged == '1' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
      - name: install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: get packages
        run: flutter pub get
      - name: generate icons
        run: make icons
      - name: generate screenshots
        uses: reactivecircus/android-emulator-runner@v2
        if: ${{ needs.check-screenshots-and-icons.outputs.screenshots-count == 'false' }}
        with:
          api-level: 32
          target: google_apis
          arch: x86_64
          profile: pixel_5
          script: make screenshots
      - name: frame screenshots
        if: ${{ needs.check-screenshots-and-icons.outputs.screenshots-count == 'false' }}
        run: |
          mv generated/screenshots/android/* android/fastlane/screenshots/en-US/
          cd android && fastlane frameit_now && rm -f $(ls -d fastlane/screenshots/en-US/* | grep -v -e '.*_framed.png')
      - name: upload android assets
        uses: actions/upload-artifact@v3
        with:
          name: android-assets-${{ needs.check-tagged.outputs.version }}
          path: android/app/src/main/res/
      - name: upload ios assets
        uses: actions/upload-artifact@v3
        with:
          name: ios-assets-${{ needs.check-tagged.outputs.version }}
          path: ios/Runner/Assets.xcassets/
      - name: upload android screenshots
        if: ${{ needs.check-screenshots-and-icons.outputs.screenshots-count == 'false' }}
        uses: actions/upload-artifact@v3
        with:
          name: android-screenshots-${{ needs.check-tagged.outputs.version }}
          path: android/fastlane/screenshots/en-US/
      - name: upload ios screenshots
        if: ${{ needs.check-screenshots-and-icons.outputs.screenshots-count == 'false' }}
        uses: actions/upload-artifact@v3
        with:
          name: ios-screenshots-${{ needs.check-tagged.outputs.version }}
          path: generated/screenshots/ios/

  build-app:
    name: build apps
    runs-on: macos-12
    if: ${{ needs.check-tagged.outputs.tagged == '1' }}
    needs:
      - check-tagged
      - generate-screenshots-and-icons
    environment: prod
    env:
      APP_ID: ${{ vars.APP_ID }}
      APP_LABEL: ${{ vars.APP_LABEL }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - name: install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}
      - name: download android assets
        uses: actions/download-artifact@v3
        with:
          name: android-assets-${{ needs.check-tagged.outputs.version }}
          path: android/app/src/main/res/
      - name: get packages
        run: flutter pub get
      - name: build aab
        run: |
          echo keyAlias=upload > android/key.properties
          echo storeFile=./upload.jks >> android/key.properties
          echo "keyPassword=$ANDROID_KEY_PASS" >> android/key.properties
          echo "storePassword=$ANDROID_KEY_STORE_PASS" >> android/key.properties
          chmod 0400 android/key.properties
          echo $KEY_STORE_DATA | base64 -d > android/app/upload.jks
          chmod 0400 android/app/upload.jks
          flutter build appbundle --release
          flutter build apk --release --split-per-abi
          rm -f android/key.properties android/app/upload.jks
        env:
          KEY_STORE_DATA: ${{ secrets.KEY_STORE_DATA }}
          ANDROID_KEY_PASS: ${{ secrets.ANDROID_KEY_PASS }}
          ANDROID_KEY_STORE_PASS: ${{ secrets.ANDROID_KEY_STORE_PASS }}
      - name: upload release aab
        uses: actions/upload-artifact@v3
        with:
          name: release-aab-${{ needs.check-tagged.outputs.version }}
          path: build/app/outputs/bundle/release/
      - name: upload release apk
        uses: actions/upload-artifact@v3
        with:
          name: release-apk-${{ needs.check-tagged.outputs.version }}
          path: build/app/outputs/flutter-apk/*.apk 
